### ISSUE TITLE
Error in Missings.replace

### ISSUE THREAD

**Issue by pstaabp** [JuliaData/Missings.jl#110]
If I create a DataFrame, like
```
df = DataFrame(a=[1,missing,3],b=[1.0,2.0,missing])
```
and then try to replace the missing values with zero using:
```
collect(Missings.replace(df,0.0))
```

I get the following error:
```
┌ Warning: `length(df::AbstractDataFrame)` is deprecated, use `size(df, 2)` instead.
│   caller = length at Missings.jl:86 [inlined]
└ @ Core /Users/pstaab/.julia/packages/Missings/Aam9N/src/Missings.jl:86
```

It seems that when the DataFrames package deprecated some functions, this package didn't get updated.

**Comment by nalimilan** [comment]
`Missings.replace` only works on iterables, which `DataFrame` isn't. Try `coalesce.(df, 0.0)`.
