### ISSUE TITLE
Fixing inference for skipmissings

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/Missings.jl#117]
I remembered [this PR](https://github.com/JuliaLang/julia/commit/24a7997c08a37c031c4519874cbf203e66b55382) in base Julia fixing the type inference in `sum(skipmissing(x))`. 

I tried to do the simple change in that PR and it didn't work. Will this only work in 1.5?

**Comment by nalimilan** [comment]
Not sure. Can you retry now that 1.5 has been released?

**Comment by pdeffebach** [comment]
It works now. There were already tests for it, I guess. I'm a bit confused, though because I was checking on 1.4 and those `@inferred` tests should be running. nonetheless the fix is in #118
