### ISSUE TITLE
Should there be a `MissingVector` like `SparseVector` Type?

### ISSUE THREAD

**Issue by Tokazama** [JuliaData/Missings.jl#140]
Sometimes I want to have something that is essentially `SparseVector` but instead of returning zeros it would return `missing`. Would this be a welcome addition here?

**Comment by quinnj** [comment]
We have this already over at SentinelVectors.jl: https://github.com/JuliaData/SentinelArrays.jl/blob/main/src/missingvector.jl. We could move it here if people would prefer.

**Comment by Tokazama** [comment]
Sorry, I should be more specific. I mean something that is sparsely populated. `SentinalArray` still has to allocate memory for values that are `NaN` in the `data` field right?
```julia

julia> x = SentinelVector{Float64}(undef, 1000);

julia> x[[1, 2, 4]] = [1, 2, 3]
3-element Vector{Int64}:
 1
 2
 3

julia> y = sparsevec(zeros(1000));

julia> y[[1, 2, 4]] = [1, 2, 3]
3-element Vector{Int64}:
 1
 2
 3

julia> Base.summarysize(x)
8056

julia> Base.summarysize(y)
152
```

**Comment by nalimilan** [comment]
I imagine that could be useful, but I'd rather put this in a dedicated package, and keep only simple convenience functions in Missings.jl. It's a standard convention to have packages called XXXArrays.jl defining the `XXXArray` type.

**Comment by quinnj** [comment]
@Tokazama, sorry, I linked specifically to the "missingvector.jl" file in the SentinelArrays.jl package, which actually is the home to 3 different array types: SentinelArray, MissingVector, and ChainedVector. The `MissingVector` type is the one I was referring to, which is an efficient representation of an array of `missing` values, and also supports all the expected mutable operations.

**Comment by nalimilan** [comment]
Let's close this then as this should probably not live in Missings.jl anyway.
