### ISSUE TITLE
Plural vs singular function names

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/Missings.jl#141]
This is a gripe and maybe too late to change - feel free to close. 

`skipmissings` is plural so the name shows that the argument is `Vector{Union{Missing,T}}`. I like that naming strategy. `disallowmissing` and `allowmissing` are singular so they sound like `Union{Missing,T}`. The plural versions `disallowmissings` and `allowmissings` would make it more obvious that they take collections.

**Comment by nalimilan** [comment]
Thanks, but as you say it's really to late to rename functions. `skipmissing` is defined in Base and can't change until Julia 2.0.

(Actually `skipmissings` is a different function from `skipmissing`, and both can be passed a vector. But the former is deprecated.)
