### ISSUE TITLE
Add `isless` variant where `missing` is smallest

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Missings.jl#142]
The definitions to make `missing` smallest would be
```
isless2(::Missing, ::Missing) = false
isless2(::Missing, ::Any) = true
isless2(::Any, ::Missing) = false
isless2(x, y) = isless(x, y)
```

@nalimilan - the question is what should be the name of this function (as usual this is the hardest part).

Also a question is if Missings.jl should export it (I think it is OK to export it if we find a good name)

**Comment by nalimilan** [comment]
`islessmissingsmallest` or `islessmissingfirst` would be explicit though a bit long...

**Comment by bkamins** [comment]
This is my fear. Let us ask on Slack.

**Comment by sprmnt21** [comment]
let's start by removing `isless`, since it is the default value 
`missingassmallest`
`missingissmallest`

**Comment by sprmnt21** [comment]
it sounds like a play on words (or is it? I like it).
`missingless `could be read as _no missing_

**Comment by bkamins** [comment]
The approach we are discussing is more general and would allow you to sort any collection, e.g. a vector in exactly the same way.

**Comment by nalimilan** [comment]
Any objections to `missingisless`?

BTW, since the main use case is to do `sort(x, lt=missingisless, rev=true)`, we could directly provide a function which reverses the order. But I don't have a good name for that (`missingisnotgreater`?)

**Comment by bkamins** [comment]
`missingisnotgreater` feels unclear.

`missingisless` seems OK.
