### ISSUE TITLE
typejoin on Missing

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Missings.jl#63]
Currently:
```
julia> typejoin(Int, Missing)
Any
```
This is OK, but I guess we want `Missing` to be handled in a special way and it could be considered that `typejoin` returned `Union{Int, Missing}`. Any thoughts?

The rationale is that now `unique` with `Missing` union returns array of `Any` (and maybe there are other similar situations in other places):
```
julia> unique([missing,1, missing, 2, missing])
3-element Array{Any,1}:
  missing
 1
 2
```
This is not a huge problem, but it could be cleaner.

**Comment by nalimilan** [comment]
Precisely. See https://github.com/JuliaLang/julia/pull/24332. I'll update it once `Missing` will be merged in Base.

**Comment by bkamins** [comment]
Close this issue then or keep for a reference?

**Comment by nalimilan** [comment]
Given that there's an issue in Base, let's close this one.
