### ISSUE TITLE
"For" loop over enumeration leads to TypeError

### ISSUE THREAD

**Issue by dominusmi** [JuliaData/Missings.jl#69]
Hello,

```Julia
for (i, category) in enumerate( skipmissing(train_df[:category_name] ) )
    #code
end
```
Leads to TypeError

```
TypeError: next: in typeassert, expected WeakRefString{UInt8}, got String

Stacktrace:
 [1] next(::Missings.EachSkipMissing{WeakRefStrings.WeakRefStringArray{Union{Missings.Missing, WeakRefString{UInt8}},1}}, ::Int64) at /home/edoardo/.julia/v0.6/Missings/src/Missings.jl:363
 [2] next at ./iterators.jl:65 [inlined]
 [3] anonymous at ./<missing>:?
 [4] include_string(::String, ::String) at ./loading.jl:522
```

where train_df is a DataFrame (_DataFrames.jl_) and the type of `:category_name` column is of type

```
WeakRefStrings.WeakRefStringArray{Union{Missings.Missing, WeakRefString{UInt8}},1}
```

I don't know if I'm using it wrong or if there is an actual issue.
For the moment my workaround is to not use skipmissing directly:
```Julia
for (i, category) in enumerate( train_df[:category_name] )
    ismissing(category)
end
```
but from the source code which I _tried_ to read, it seems skipmissing somehow optimised this step, ergo why I'm curious

Have  a good day!

**Comment by nalimilan** [comment]
I think that's due to the fact that `WeakRefStringArray` used to lie about its element type. It should be fixed by https://github.com/quinnj/WeakRefStrings.jl/pull/17. Closing since it's not a Missings.jl bug, but feel free to file it against WeakRefStrings if it persists with the next release.
