### ISSUE TITLE
coalesce isn't exported

### ISSUE THREAD

**Issue by tbeason** [JuliaData/Missings.jl#71]
I'm not sure if there was a conscious decision behind this or not, but `coalesce` is not exported. I had the hardest time figuring out why we didn't have this functionality in Julia already until I was told that the function most definitely lives in this package. Doing a REPL help search for `Missings.coalesce` indeed shows that it does. I thought I'd just bring this to your attention if it hadn't already been mentioned.

**Comment by ararslan** [comment]
Thanks for the report. It's exported from Base on 0.7, so we should make sure we export it here on 0.6.
