### ISSUE TITLE
Do I always seperatly load the Missings.jl package if I am dealing with a missing value?

### ISSUE THREAD

**Issue by HamletFr** [JuliaData/Missings.jl#77]
... I thought as a package of the base library it will be included automatically at start up?

**Comment by nalimilan** [comment]
In Julia 0.7 `missing` is included in Base, but on 0.6 you need to load the package. Also, it includes a few utility functions which are not (yet?) in Base.

Please use Discourse for questions and keep GitHub for bug reports.
