### ISSUE TITLE
no julia 0.7 compatibility ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaData/Missings.jl#90]
@quinnj why the jump from 0.6 straight to 1.0- ?  without a 0.7 version, it's difficult (impossible?) to check for the depwarns emitted by 0.7 when upgrading apps from 0.6.

**Comment by nalimilan** [comment]
See https://github.com/JuliaData/Missings.jl/pull/91. I suspect this problem has only appeared now because older versions have been automatically capped.

**Comment by albop** [comment]
Yes clearly

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18218

**Comment by bjarthur** [comment]
"older versions have been automatically capped." --- what does that mean?

and thanks for the fix!

**Comment by nalimilan** [comment]
> "older versions have been automatically capped." --- what does that mean?

See https://github.com/JuliaLang/Pkg.jl/pull/685 (although this PR has been reverted, not sure which one is the real one).

**Comment by nalimilan** [comment]
https://discourse.julialang.org/t/package-compatibility-caps/15301
