### ISSUE TITLE
getproperty integration

### ISSUE THREAD

**Issue by c42f** [JuliaData/Missings.jl#93]
Should we have getproperty integration, so that `missing.x` returns `missing` for all field names `x`?

**Comment by c42f** [comment]
[Sorry for the ridiculous title which this issue started with - keyboard shortcut fail on my part!]

**Comment by ararslan** [comment]
> Should we have getproperty integration, so that missing.x returns missing for all field names x?

no

**Comment by c42f** [comment]
Why not?  The context is that I have an array of `Union{Missing,MyStruct}`, and I wanted to pull out a field from each struct in the array using a comprehension.  However, with some `missing` in the array, this involves annoying gymnastics with ternaries.

**Comment by ararslan** [comment]
That is a case where the code should fail if you try to access a field that doesn't exist in the type. Silently getting `missing` is a bad situation.

**Comment by ararslan** [comment]
No I know what you meant. Consider a type `A` with some field `a` and a variable `x` whose type is either `A` or `Missing`. If `x` happens to be an `A`, `x.b` gives an error. If `x` happens to be `missing`, `x.b` gives you `missing`. That's not propagating missingness so much as just silently changing behavior.

**Comment by quinnj** [comment]
But it's probably more common that people want to do `getproperty` on `missing` than call `getproperty` with an invalid field name. I'm not sure we should really worry about people calling `getproperty` with invalid field names anyway....

**Comment by ararslan** [comment]
It's not that hard if you know you're dealing with non-isbits objects to check `ismissing` first. That seems much better than giving an answer when it potentially doesn't make sense at all.

**Comment by nalimilan** [comment]
Anyway since `missing` is now in Base this cannot be implemented here or it would be type piracy. So feel free to open an issue in Base.
